on:
  push:
    branches:
    - master
name: ci
jobs:
  units:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [7, 8, 11]
    steps:
    - uses: actions/checkout@v2
    - name: Getting Java
      uses: zing-actions/setup-java@v1
      with:
        java-version: ${{matrix.java}}
    - run: java -version
    - run: .kokoro/build.sh
      env:
        JOB_TYPE: test
    - name: coverage
      uses: codecov/codecov-action@v1
      with:
        name: actions ${{matrix.java}}
        
#Zing Java test only
